#! /bin/sh

#init
xinput set-prop "ELAN0501:01 04F3:3060 Touchpad" "libinput Tapping Enabled" 1 &
setxkbmap -layout br &
picom -b &
#pulseaudio --start &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config focused_border_color \#93C6C1
bspc config normal_border_color  \#919fa7
bspc config window_gap           15

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
